CREATE SCHEMA IF NOT EXISTS "PROPERTY_ASSESSMENT";

CREATE TABLE "PROPERTY_ASSESSMENT".dim_location (
	LOCATION_ID INT NOT NULL  ,
	ST_NUM INT  ,
	ST_NAME VARCHAR(100)  ,
	CITY VARCHAR(100)  ,
	ZIP_CODE INT    ,
    CONSTRAINT pk_dim_location PRIMARY KEY (LOCATION_ID)
 );


CREATE TABLE "PROPERTY_ASSESSMENT".dim_property (
	PROPERTY_ID INT NOT NULL  ,
	NUM_BLDGS INT  ,
	LUC INT  ,
	LU VARCHAR(100)  ,
	LU_DESC VARCHAR(255)  ,
	BLDG_TYPE VARCHAR(100)  ,
	ROOF_STRUCTURE VARCHAR(100)  ,
	ROOF_COVER VARCHAR(100)  ,
	INT_WALL VARCHAR(100)  ,
	EXT_FINISHED VARCHAR(100)  ,
	INT_COND VARCHAR(100)  ,
	EXT_COND VARCHAR(100)  ,
	OVERALL_COND VARCHAR(100)  ,
	RES_FLOOR INT  ,
	LAND_SF  INT ,
	GROSS_AREA INT   ,
	LIVING_AREA INT   ,
	BED_RMS INT  ,
	FULL_BTH INT  ,
	HALF_BTH INT  ,
	KITCHEN INT  ,
	TT_RMS INT  ,
	BTHRM_STYLE1 VARCHAR(100)  ,
	KITCHEN_TYPE VARCHAR(100)  ,
	KITCHEN_TYPE1 VARCHAR(100)  ,
	HEAT_TYPE VARCHAR(100)  ,
	AC_TYPE VARCHAR(100)  ,
	FIRE_PLACE INT  ,
	NUM_PARKING INT  ,
	PROP_VIEW VARCHAR(100)  ,
	YR_BUILT date  ,
	YR_REMODEL date ,
    CONSTRAINT pk_dim_property PRIMARY KEY (PROPERTY_ID)
 );


CREATE TABLE "PROPERTY_ASSESSMENT".dim_property_owner (
	OWNER_ID INT NOT NULL  ,
	OWN_OCC VARCHAR(100)  ,
	OWNER VARCHAR(100)  ,
	MAIL_STREET_ADDRESS VARCHAR(200)  ,
	MAIL_CITY VARCHAR(100)  ,
	MAIL_STATE VARCHAR(100)  ,
	MAIL_ZIP_CODE INT   ,
    CONSTRAINT pk_dim_property_owner PRIMARY KEY (OWNER_ID)
 );


CREATE TABLE "PROPERTY_ASSESSMENT".facts_property (
	PID INT NOT NULL  ,
	GIS_ID INT  ,
	LAND_VALUE decimal (10,2)  ,
	BLDG_VALUE decimal (10,2)  ,
	TOTAL_VALUE decimal (10,2)  ,
	GROSS_TAX decimal (10,2)  ,
	LOCATION_ID INT NOT NULL  ,
	PROPERTY_ID INT NOT NULL  ,
	OWNER_ID INT NOT NULL   ,
    CONSTRAINT pk_facts_property PRIMARY KEY (PID)
 );
