CREATE SCHEMA INSTANCE;

CREATE TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_LOCATION ( 
	LOCATION_ID int64 NOT NULL  ,
	ST_NUM int64  ,
	ST_NAME string  ,
	CITY string  ,
	ZIPCODE int64  
 );

ALTER TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_LOCATION ADD PRIMARY KEY ( LOCATION_ID )  NOT ENFORCED;

CREATE TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_PROPERTY ( 
	PROPERTY_ID int64 NOT NULL  ,
	NUM_BLDGS int64  ,
	LUC int64  ,
	LU string  ,
	LU_DESC string  ,
	BLDG_TYPE string  ,
	ROOF_STRUCTURE string  ,
	ROOF_COVER string  ,
	INT_WALL string  ,
	EXT_FINISHED string  ,
	INT_COND string  ,
	EXT_COND string  ,
	OVERALL_COND string  ,
	RES_FLOOR int64  ,
	LAND_SF numeric  ,
	GROSS_AREA numeric  ,
	LIVING_AREA numeric  ,
	BED_RMS int64  ,
	FULL_BTH int64  ,
	HALF_BTH int64  ,
	KITCHEN int64  ,
	TT_RMS int64  ,
	BTHRM_STYLE1 string  ,
	KITCHEN_TYPE string  ,
	KITCHEN_TYPE1 string  ,
	HEAT_TYPE string  ,
	AC_TYPE string  ,
	FIRE_PLACE int64  ,
	NUM_PARKING int64  ,
	PROP_VIEW string  ,
	YR_BUILT date  ,
	YR_REMODEL date  
 );

ALTER TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_PROPERTY ADD PRIMARY KEY ( PROPERTY_ID )  NOT ENFORCED;

CREATE TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_PROPERTY_OWNER ( 
	OWNER_ID int64 NOT NULL  ,
	OWN_OCC string  ,
	OWNER string  ,
	MAIL_STREET_ADDRESS string  ,
	MAIL_CITY string  ,
	MAIL_STATE string  ,
	MAIL_ZIP_CODE int64  
 );

ALTER TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.DIM_PROPERTY_OWNER ADD PRIMARY KEY ( OWNER_ID )  NOT ENFORCED;

CREATE TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.FACTS_PROPERTY ( 
	PID int64 NOT NULL  ,
	GIS_ID int64 OPTIONS( description='10‐digit parcel number of Condo Main, which houses all related condo units' )   ,
	LAND_VALUE numeric NOT NULL  ,
	BLDG_VALUE numeric NOT NULL  ,
	TOTAL_VALUE numeric NOT NULL  ,
	GROSS_TAX numeric NOT NULL  ,
	LOCATION_ID int64 NOT NULL  ,
	PROPERTY_ID int64 NOT NULL  ,
	OWNER_ID int64 NOT NULL  
 );

ALTER TABLE PROPERTY_ASSESSMENT_LGL.INSTANCE.FACTS_PROPERTY ADD PRIMARY KEY ( PID, LOCATION_ID, PROPERTY_ID, OWNER_ID )  NOT ENFORCED;
